name: Update NSE Stocks to Google Sheet

on:
  schedule:
    # Yeh samay 14:45 UTC hai, jiska matlab Bharat mein raat 8:15 PM hai
    - cron: '45 14 * * 1-5'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install gspread oauth2client pandas requests

      - name: Run Python Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        # GitHub ke naye structure ke mutabik sahi rasta (Path)
        run: python update_sheet.py
